name: deep-course
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scikit-learn
  - Pillow
  - tqdm
  - tensorboard
  - matplotlib
  - seaborn
  - albumentations
  - wandb
  - mlflow
  - jupyter
  - ipython
  - pip
  - librosa
  - cudatoolkit=11.8
  - cudnn=8.9.2.26
  - pip:
    - tensorflow==2.8.0
    - jupytext
