name: deep-course
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scikit-learn=1.5.1
  - Pillow
  - tqdm
  - tensorboard
  - matplotlib
  - seaborn
  - albumentations
  - wandb
  - mlflow
  - jupyter
  - ipython
  - pip
  - cudatoolkit==11.8
  - cudnn=8.8
  - pip:
    - tensorrt==8.5.3.1
    - tensorflow==2.13.0
    - tensorflow_hub==0.13.0
    - scikeras==0.12.0
    - jupytext
